name: Build and Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build and tag Docker image
        run: |
          docker build --build-arg token=${{ secrets.Discord_Token}} -t ${{ secrets.DOCKER_HUB_USERNAME }}/chatty:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/chatty:latest

      - name: Update image metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/chatty:latest
          tags: |
            type=sha
          labels: |
            org.opencontainers.image.title=chatty 
            org.opencontainers.image.description=chatty bot
            org.opencontainers.image.url=https://github.com/${{github.repository}}
            org.opencontainers.image.revision=${{github.sha}}
            org.opencontainers.image.licenses=MIT
