name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker Layers
      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: |
            /tmp/.buildx-cache
            ~/.cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      # Run Linter (optional, replace with your linter script)
      - name: Run Linter
        run: npm run lint

      # Run Tests (optional, replace with your test script)
      - name: Run Tests
        run: npm test

      # Build and Push Docker Image with caching
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --cache-from=type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/chatty:cache \
            --cache-to=type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/chatty:cache,mode=max \
            --build-arg token=${{ secrets.Discord_Token }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/chatty:latest \
            --push .

      # Update Image Metadata
      - name: Update Image Metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/chatty:latest
          tags: |
            type=sha
          labels: |
            org.opencontainers.image.title=Chatty 
            org.opencontainers.image.description=Chatty bot
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=MIT

      # Verify the built Docker image
      - name: Verify Build
        run: docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/chatty:latest node --version
